/**
 * background/heuristics/lengthAndEntropy.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Heuristic: URL length and subdomain/path entropy.
 *
 * Detects:
 * 1. Abnormally long URLs (common in phishing to hide the real domain)
 * 2. High Shannon entropy in subdomains or paths (random-looking strings
 *    generated by phishing kits, e.g. "xk4jq2ab.phish.com")
 *
 * Pure function — no imports of mutable state, fully testable in isolation.
 */

import type { HeuristicResult, NormalizedUrl, PageSignals } from '../../shared/types';
import { HEURISTIC_WEIGHTS, URL_ANALYSIS } from '../../shared/constants';

const RULE_ID = 'heuristic:length_entropy';

/**
 * Analyze URL length and subdomain/path entropy.
 */
export function analyzeLengthAndEntropy(
  normalizedUrl: NormalizedUrl,
  _pageSignals: PageSignals | null
): HeuristicResult {
  const { normalized, hostname, path } = normalizedUrl;

  // ── Length check ──────────────────────────────────────────────────────────
  const urlLength = normalized.length;
  const isTooLong = urlLength > URL_ANALYSIS.SUSPICIOUS_LENGTH;

  // ── Entropy check ─────────────────────────────────────────────────────────
  // Calculate entropy on the subdomain labels (exclude the registered domain)
  // and the path, which are the parts attackers randomize.
  const subdomainPart = extractSubdomainPart(hostname);
  const analysisString = subdomainPart + path;

  const entropy = shannonEntropy(analysisString);
  const isHighEntropy = entropy > URL_ANALYSIS.SUSPICIOUS_ENTROPY;

  const triggered = isTooLong || isHighEntropy;

  if (!triggered) {
    return {
      ruleId: RULE_ID,
      name: 'URL Length & Entropy',
      triggered: false,
      weight: HEURISTIC_WEIGHTS.LENGTH_ENTROPY,
      explanation: 'URL length and structure appear normal.',
    };
  }

  const reasons: string[] = [];
  if (isTooLong) {
    reasons.push(`URL is unusually long (${urlLength} chars — threshold: ${URL_ANALYSIS.SUSPICIOUS_LENGTH})`);
  }
  if (isHighEntropy) {
    reasons.push(`Subdomain/path appears randomized (entropy: ${entropy.toFixed(2)} — threshold: ${URL_ANALYSIS.SUSPICIOUS_ENTROPY})`);
  }

  return {
    ruleId: RULE_ID,
    name: 'URL Length & Entropy',
    triggered: true,
    weight: HEURISTIC_WEIGHTS.LENGTH_ENTROPY,
    explanation: reasons.join('; '),
  };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Calculate Shannon entropy of a string.
 * Higher entropy → more random-looking content.
 * Range: 0 (single character) to log2(alphabet_size) (~4.7 for lowercase alpha).
 */
export function shannonEntropy(str: string): number {
  if (str.length === 0) return 0;

  const freq = new Map<string, number>();
  for (const char of str) {
    freq.set(char, (freq.get(char) ?? 0) + 1);
  }

  let entropy = 0;
  for (const count of freq.values()) {
    const p = count / str.length;
    entropy -= p * Math.log2(p);
  }

  return entropy;
}

/**
 * Extract the subdomain part (everything before the registered domain).
 * e.g. "secure.paypal-verify.attacker.com" → "secure.paypal-verify"
 * e.g. "paypal.com" → "" (no subdomain)
 */
function extractSubdomainPart(hostname: string): string {
  const labels = hostname.split('.');
  if (labels.length <= 2) return '';
  // Check for two-part TLD (co.uk style) — but for entropy purposes,
  // even a rough approximation is fine.
  return labels.slice(0, -2).join('.');
}
